# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "673c3432a54a7176547f5ab3126bec7d"
name = "cart-checkout-validation-app"
handle = "cart-checkout-validation-app-2"
application_url = "https://common-interest-lately-spam.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "llama-farm.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://common-interest-lately-spam.trycloudflare.com/auth/callback",
  "https://common-interest-lately-spam.trycloudflare.com/auth/shopify/callback",
  "https://common-interest-lately-spam.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
